export const GET_BIBLES = "GET_BIBLES";
export const GET_BIBLES_ERROR = "GET_BIBLES_ERROR";
export const GET_BIBLE_BOOKS = "GET_BIBLE_BOOKS";
export const GET_BIBLE_BOOKS_ERROR = "GET_BIBLE_BOOK_ERROR";
export const GET_BIBLE_BOOK_CHAPTERS = "GET_BIBLE_BOOK_CHAPTERS";
export const GET_BIBLE_BOOK_CHAPTERS_ERROR = "GET_BIBLE_BOOK_CHAPTERS_ERROR";
export const GET_SINGLE_CHAPTER = "GET_SINGLE_CHAPTER";
export const GET_SINGLE_CHAPTER_ERROR = "GET_SINGLE_CHAPTER_ERROR";
export const GET_CHAPTER_VERSE = "GET_CHAPTER_VERSE";
export const GET_CHAPTER_VERSE_ERROR = "GET_CHAPTER_VERSE_ERROR";

export const SIGNUP = "SIGNUP";
export const SIGNUP_ERROR = "SIGNUP_ERROR";
export const LOGIN = "LOGIN";
export const LOGIN_ERROR = "LOGIN_ERROR";
