export const GET_BIBLES = "GET_BIBLES";
export const GET_BIBLES_ERROR = "GET_BIBLES_ERROR";
export const GET_BIBLE_BOOKS = "GET_BIBLE_BOOKS";
export const GET_BIBLE_BOOKS_ERROR = "GET_BIBLE_BOOK_ERROR";
export const GET_BIBLE_BOOK_CHAPTERS = "GET_BIBLE_BOOK_CHAPTERS";
export const GET_BIBLE_BOOK_CHAPTERS_ERROR = "GET_BIBLE_BOOK_CHAPTERS_ERROR";
export const GET_SINGLE_CHAPTER = "GET_SINGLE_CHAPTER";
export const GET_SINGLE_CHAPTER_ERROR = "GET_SINGLE_CHAPTER_ERROR";
export const GET_CHAPTER_VERSE = "GET_CHAPTER_VERSE";
export const GET_CHAPTER_VERSE_ERROR = "GET_CHAPTER_VERSE_ERROR";

export const SIGNUP = "SIGNUP";
export const SIGNUP_ERROR = "SIGNUP_ERROR";
export const LOGIN = "LOGIN";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOAD_USER = "LOAD_USER";
export const LOAD_USER_ERROR = "LOAD_USER_ERROR";
export const LOGOUT = "LOGOUT";

export const SAVE_VERSE = "SAVE_VERSE";
export const SAVE_VERSE_ERROR = "SAVE_VERSE_ERROR";
export const GET_USER_VERSES = "GET_USER_VERSES";
export const GET_USER_VERSES_ERROR = "GET_USER_VERSES_ERROR";
export const GET_VERSE_BY_ID = "GET_VERSE_BY_ID";
export const GET_VERSE_BY_ID_ERROR = "GET_VERSE_BY_ID_ERROR";
export const GET_VERSE_VERSION = "GET_VERSE_VERSION";
export const GET_VERSE_VERSION_ERROR = "GET_VERSE_VERSION_ERROR";

export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT ";

export const DELETE_VERSE = "DELETE_VERSE";
export const DELETE_VERSE_ERROR = "DELETE_VERSE_ERROR";

export const FILTERED_VERSE = "FILTERED_VERSE";
export const CLEAR_FILTERED_VERSE = "CLEAR_FILTERED_VERSE";
