export const GET_BIBLES = "SGET_BIBLES";
export const GET_BIBLES_ERROR = "SGET_BIBLES_ERROR";
export const GET_BIBLE_BOOKS = "GET_BIBLE_BOOKS";
export const GET_BIBLE_BOOKS_ERROR = "GET_BIBLE_BOOK_ERROR";
